[project]
name = "geha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.126.0",
    "langchain-core>=1.6,<2",
    "langgraph>=1,<2",
    "langgraph-checkpoint-sqlite>=3,<4",
    "langchain-text-splitters>=1.1.2",
    "langfuse>=4,<5",
    "openai>=3.13.0",
    "pdfplumber>=0.11,<1",
    "pillow>=11,<13",
    "pypdfium2>=5,<6",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.45,<2",
    "temporalio>=1.32.0",
    "langchain-classic>=1.0.8",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.2",
    "rank-bm25>=0.2.2",
    "langchain>=1.4.2",
    "loguru>=0.7.3",
    "rich>=15.0.0",
    "unstructured[pdf]>=0.27.8",
    "chromadb>=1.5.9",
    "matplotlib>=3.11.2",
    "jsonargparse>=4.52.0",
    "pymupdf>=1.28.2",
    "cohere>=7.1.1",
    "langchain-ollama>=1.1.0",
]
